// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFasUOBBHQD2UnsB4ikaYtbA1_Neoqh8I',
    appId: '1:341557183197:web:474e2b992ff67f6894d134',
    messagingSenderId: '341557183197',
    projectId: 'flutter-giftcon',
    authDomain: 'flutter-giftcon.firebaseapp.com',
    databaseURL: 'https://flutter-giftcon-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-giftcon.appspot.com',
    measurementId: 'G-N13HNJ419W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdP1xVanS4oNnGvA6Rex-hK6h0-wSnXV8',
    appId: '1:341557183197:android:5e371cec550e307c94d134',
    messagingSenderId: '341557183197',
    projectId: 'flutter-giftcon',
    databaseURL: 'https://flutter-giftcon-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-giftcon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2plLk2_QsyoW1lGkHC62X_1Yz0rnC5b4',
    appId: '1:341557183197:ios:26553c97a23c99b594d134',
    messagingSenderId: '341557183197',
    projectId: 'flutter-giftcon',
    databaseURL: 'https://flutter-giftcon-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-giftcon.appspot.com',
    iosClientId: '341557183197-u5fqdkufji8mfbggptf5l6pqmv1bcul9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationGiftcon',
  );
}
